---
settings:
  name: VSC, VASA Provider, and SRA 9.7
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: VSC、VASA Provider和SRA文档
    url: "/index.html"
  - title: 发行说明
    url: "/release-notes.html"
  - title: 快速入门
    url: "/qsg.html"
  - section: deploy
  - section: manage
  - title: 法律声明
    url: "/legal-notices.html"
