---
permalink: deploy/concept-configure-your-storage-system-environment.html 
sidebar: sidebar 
keywords: configuring, virtual, storage, console, vmware, vsphere, storage, system, environment, 
summary: 适用于VMware vSphere的Virtual Storage Console提供了一种机制来发现存储系统并设置存储凭据。这些凭据提供了 Virtual Storage Console （ VSC ）用户使用存储系统执行任务所需的 ONTAP 权限。 
---
= 为VMware vSphere存储系统环境配置Virtual Storage Console
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
适用于VMware vSphere的Virtual Storage Console提供了一种机制来发现存储系统并设置存储凭据。这些凭据提供了 Virtual Storage Console （ VSC ）用户使用存储系统执行任务所需的 ONTAP 权限。

VSC 必须先发现存储系统，然后才能显示和管理存储资源。在发现过程中，您必须提供存储系统的 ONTAP 凭据。这些特权（或角色）与分配给每个存储系统的用户名和密码对关联。这些用户名和密码对使用 ONTAP 基于角色的访问控制（ Role-Based Access Control ， RBAC ），必须在 ONTAP 中进行设置。您不能在 VSC 中更改这些凭据。您可以使用定义ONTAP RBAC角色。

[NOTE]
====
如果您以管理员身份登录，则会自动拥有该存储系统的所有特权。

====
将存储系统添加到 VSC 时，必须提供存储系统的 IP 地址以及与该系统关联的用户名和密码对。您可以设置 VSC 在存储系统发现过程中要使用的默认凭据，也可以在发现存储系统后手动输入凭据。添加到 VSC 的存储系统的详细信息会自动推送到您在部署中启用的扩展。您无需手动向 VASA Provider 和 Storage Replication Adapter （ SRA ）添加存储。VSC和SRA均支持在集群级别和级别添加凭据。VASA Provider 仅支持使用集群级别的凭据来添加存储系统。

如果您的环境包含多个 vCenter Server 实例，则在从存储系统页面向 VSC 添加存储系统时，添加存储系统对话框会显示一个 vCenter Server 框，您可以在此框中指定要将存储系统添加到哪个 vCenter Server 实例。如果您通过右键单击数据中心名称来添加存储系统，则无法指定 vCenter Server 实例，因为服务器已与该数据中心关联。

发现可通过以下方式之一进行。在每种情况下，您都必须为任何新发现的存储系统提供凭据。

* VSC 服务启动后， VSC 将开始自动后台发现过程。
* 您可以单击"存储系统"页面中的*重新发现全部*按钮、也可以在主机或数据中心上单击此按钮、以从*操作*菜单中选择此按钮(菜单：操作[NetApp VSC >更新主机和存储数据])。您也可以单击概述部分的入门选项卡上的 * 发现 * 。


所有 VSC 功能都需要特定的权限才能执行任务。您可以根据与 ONTAP 角色关联的凭据限制用户可以执行的操作。具有相同存储系统用户名和密码对的所有用户都共享一组相同的存储系统凭据，并可执行相同的操作。
