---
permalink: deploy/reference-copyright.html 
sidebar: sidebar 
keywords: copyright 
summary: 版权 
---
= 版权
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


版权所有 © 2020 NetApp ， Inc. 。保留所有权利。Printed in the U.S.

版权所涵盖的本文档的任何部分不得以任何形式或任何方式复制，包括图像，电子或机械，包括影印，录制， 在未经版权所有者事先书面许可的情况下，在电子检索系统中粘贴或存储。

Software derived from copyrighted NetApp material is subject to the following license and disclaimer:

THIS SOFTWARE IS PROVIDED BY NETAPP "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, WHICH ARE HEREBY DISCLAIMED.IN NO EVENT SHALL NETAPP BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

NetApp reserves the right to change any products described herein at any time, and without notice.NetApp assumes no responsibility or liability arising from the use of products described herein, except as expressly agreed to in writing by NetApp.The use or purchase of this product does not convey a license under any patent rights, trademark rights, or any other intellectual property rights of NetApp.

The product described in this manual may be protected by one or more U.S.patents, foreign patents, or pending applications.

本文所含数据与商用项目（定义见 FAR 2.101 ）相关，属于 NetApp ， Inc. 的专有信息政府拥有非独占，不可转让，不可再许可，全球有限且不可撤销的许可，仅可在与美国相关并为美国提供支持时使用此数据交付数据所依据的政府合同。除非本协议另有规定，否则不得使用，披露，复制，修改，执行， 或在未经 NetApp ， Inc. 事先书面批准的情况下显示。美国国防部的政府许可权利仅限于 DFARS 第 252.227-7015 （ b ）条中确定的权利。
