---
permalink: deploy/reference-considerations-for-deploying-virtual-appliance-for-vsc-vasa-provider-and-sra.html 
sidebar: sidebar 
keywords: considerations, requirements, deploying, virtual, appliance, vsc, vasa, provider, sra, 
summary: '在部署Virtual Storage Console (VSC)、VASA Provider和Storage Replication Adapter (SRA)虚拟设备之前、最好先对部署进行规划、并确定希望如何在环境中配置VSC、VASA Provider和SRA。' 
---
= 部署VSC、VASA Provider和SRA虚拟设备的注意事项和要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在部署Virtual Storage Console (VSC)、VASA Provider和Storage Replication Adapter (SRA)虚拟设备之前、最好先对部署进行规划、并确定希望如何在环境中配置VSC、VASA Provider和SRA。

下表简要介绍了在部署VSC、VASA Provider和SRA虚拟设备之前应考虑的事项。

[cols="1a,1a"]
|===
| 注意事项 | Description 


 a| 
首次部署VSC、VASA Provider和SRA虚拟设备
 a| 
部署VSC、VASA Provider和SRA虚拟设备时、会自动安装VSC功能。 link:concept-deploy-or-upgrade-ontap-tools.html["部署或升级VSC、VASA Provider和SRA"^]

link:concept-installation-workflow-for-new-users.html["适用于VSC、VASA Provider和SRA虚拟设备新用户的部署工作流"^]



 a| 
从现有 VSC 部署升级
 a| 
将操作步骤 从现有VSC部署升级到VSC、VASA Provider和SRA虚拟设备取决于VSC的版本以及是否已部署VSC、VASA Provider和SRA。有关详细信息，请参见部署工作流和升级部分。 link:concept-installation-workflow-for-existing-users-of-vsc.html["适用于VSC、VASA Provider和SRA的现有用户的部署工作流"^]

升级前的最佳实践：

* 您应记录有关正在使用的存储系统及其凭据的信息。
+
升级后，您应验证是否已自动发现所有存储系统，以及这些存储系统是否具有正确的凭据。

* 如果您修改了任何标准 VSC 角色，则应复制这些角色以保存所做的更改。
+
每次重新启动 VSC 服务时， VSC 都会使用当前默认值覆盖标准角色。





 a| 
为 VSC 重新生成 SSL 证书
 a| 
在为VSC、VASA Provider和SRA部署虚拟设备时、系统会自动生成SSL证书。您可能需要重新生成 SSL 证书才能创建站点专用的证书。 link:task-regenerate-an-ssl-certificate-for-vsc.html["为重新生成SSL证书"^]



 a| 
设置 ESXi 服务器值
 a| 
虽然默认情况下，大多数 ESXi 服务器值都已设置，但最好检查这些值。这些值基于内部测试。根据您的环境，您可能需要更改某些值以提高性能。

* link:task-configure-esx-server-multipathing-and-timeout-settings.html["配置 ESXi 服务器多路径和超时设置"^]
* link:reference-esx-host-values-set-by-vsc-for-vmware-vsphere.html["使用适用于VMware vSphere的Virtual Storage Console设置的ESXi主机值"^]




 a| 
子操作系统超时值
 a| 
子操作系统（子操作系统）超时脚本可为支持的 Linux ， Solaris 和 Windows 子操作系统设置 SCSI I/O 超时值，以提供正确的故障转移行为。

|===
下表简要介绍了为VSC、VASA Provider和SRA配置虚拟设备所需的资源。

[cols="1a,1a"]
|===
| 注意事项 | Description 


 a| 
基于角色的访问控制（ RBAC ）的要求
 a| 
VSC 同时支持 vCenter Server RBAC 和 ONTAP RBAC 。用于向vCenter Server注册VSC的帐户(使用` https：//<appliance_ip>：8143/Register.html`)必须是vCenter Server管理员(分配给vCenter Server管理员或管理员角色)。如果您计划以管理员身份运行 VSC ，则必须具有执行所有任务所需的所有权限和特权。

如果您的公司要求您限制对 vSphere 对象的访问，您可以创建标准 VSC 角色并将其分配给用户，以满足 vCenter Server 的要求。

您可以使用VSC、VASA Provider和SRA虚拟设备随附的JSON文件使用ONTAP System Manager创建建议的ONTAP 角色。

如果用户尝试在没有正确权限的情况下执行任务，则任务选项将灰显。

* link:concept-standard-roles-packaged-with-virtual-appliance-for-vsc-vp-and-sra.html["VSC、VASA Provider和SRA虚拟设备随附的标准角色"^]
* link:concept-recommended-ontap-roles-when-using-vsc-for-vmware-vsphere.html["使用适用于VMware vSphere的VSC时的建议ONTAP 角色"^]




 a| 
ONTAP 版本
 a| 
存储系统必须运行ONTAP 9.1、9.3、9.5、9.6或9.7。



 a| 
存储功能配置文件
 a| 
要使用存储功能配置文件或设置警报，必须启用适用于 ONTAP 的 VASA Provider 。启用 VASA Provider 后，您可以配置 VMware 虚拟卷（ VVOL ）数据存储库，并且可以创建和管理存储功能配置文件和警报。

当卷或聚合容量接近全满或数据存储库不再符合相关存储功能配置文件时，警报会向您发出警告。

|===