---
permalink: deploy/task-install-the-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords: installing, the, nfs, vaai, plug-in, 
summary: '您可以使用Virtual Storage Console (VSC)、VASA Provider和Storage Replication Adapter (SRA)虚拟设备的图形用户界面安装适用于VMware vStorage APIs for Array Integration (VAAI)的NFS插件。' 
---
= 安装 NFS VAAI 插件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Virtual Storage Console (VSC)、VASA Provider和Storage Replication Adapter (SRA)虚拟设备的图形用户界面安装适用于VMware vStorage APIs for Array Integration (VAAI)的NFS插件。

.开始之前
* 您必须已从下载适用于VAAI的NFS插件的安装包(`.vib`)。
+
https://mysupport.netapp.com/site/["NetApp 支持"^]

* 您必须已安装ESXi主机6.5或更高版本以及ONTAP 9.1或更高版本。
* 您必须已启动ESXi主机并挂载NFS数据存储库。
* 您必须已将`DataMover.HardwareAcceleratedMove`、`DataMover.HardwareAcceleratedInit`和`VMFS3.HardwareAcceleratedLocking`主机设置的值设置为"`1`"。
+
更新*建议设置*对话框后、这些值将在ESXi主机上自动设置。

* 您必须已使用`vserver nfs modify -vserver vserver_name -vStorage enabled`命令在上启用vStorage选项。


.步骤
. 将从下载的`.vib`文件重命名为`NetAppNasPlugy.vib`、以匹配VSC使用的预定义名称。
. 单击VSC主页中的*设置*。
. 单击 * NFS VAAI 工具 * 选项卡。
. 单击 * 现有版本 * 部分中的 * 更改 * 。
. 浏览并选择已重命名的`.vib`文件、然后单击*上传*将此文件上传到虚拟设备。
. 在*在ESXi主机上安装*部分中、选择要安装NFS VAAI插件的ESXi主机、然后单击*安装*。
+
您应按照屏幕上的说明完成安装。您可以在 vSphere Web Client 的任务部分中监控安装进度。

. 安装完成后重新启动 ESXi 主机。
+
重新启动 ESXi 主机时， VSC 会自动检测 NFS VAAI 插件。您无需执行其他步骤即可启用此插件。


