---
permalink: manage/concept-what-storage-capabilities-are.html 
sidebar: sidebar 
keywords: storage, capability, profiles, 
summary: 存储功能是一组存储系统属性，用于确定特定级别的存储性能，存储效率以及其他功能，例如与存储功能关联的存储对象的加密。 
---
= 什么是存储功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
存储功能是一组存储系统属性，用于确定特定级别的存储性能，存储效率以及其他功能，例如与存储功能关联的存储对象的加密。

对于传统数据存储库，您可以使用存储功能配置文件一致地创建具有通用属性的数据存储库，并为其分配 QoS 策略。在配置期间， VSC 会显示与存储功能配置文件匹配的集群， SVM 和聚合。您可以使用*存储映射*菜单中的*全局自动生成配置文件*选项从现有传统数据存储库生成存储功能配置文件。创建配置文件后，您可以使用 VSC 监控数据存储库与配置文件的合规性。

与VVOL数据存储库结合使用时、配置向导可以使用多个存储功能配置文件在数据存储库中创建不同的FlexVol 卷。您可以使用虚拟机存储策略根据定义自动在适当的FlexVol 卷中为虚拟机创建VVOL。例如，您可以为通用存储类（例如性能限制和加密或 FabricPool 等其他功能）创建配置文件。您可以稍后在 vCenter Server 中创建 VM 存储策略，以表示虚拟机的业务类别，并按名称（例如生产，测试， HR ）将这些策略链接到相应的存储功能配置文件。

与VVOL结合使用时、存储功能配置文件还用于设置各个虚拟机的存储性能、并将其放置在VVOL数据存储库中最能满足性能要求的FlexVol 卷上。您可以为性能指定具有最小和 / 或最大 IOPS 的 QoS 策略。您可以在最初配置虚拟机时使用默认策略，也可以在日后业务需求发生变化时更改虚拟机存储策略。

然后， vCenter Server 会将 LUN 或卷的存储功能与该 LUN 或卷上配置的数据存储库相关联。这样，您就可以在与虚拟机的存储配置文件匹配的数据存储库中配置虚拟机，并确保数据存储库集群中的所有数据存储库都具有相同的存储服务级别。

借助Virtual Storage Console (VSC)、VASA Provider和Storage Replication Adapter (SRA)虚拟设备、您可以为每个虚拟卷(VVol)数据存储库配置一个新的存储功能配置文件、该配置文件支持在同一个VVol数据存储库上配置具有不同IOPS要求的虚拟机。在执行具有IOPS要求的虚拟机配置工作流时、所有VVol数据存储库都会列在兼容数据存储库列表中。

[NOTE]
====
在尝试为6.5之前的vCenter Server配置或修改虚拟机时、兼容数据存储库列表中仅会列出包含性能设置为`MAx_IOPS`的存储功能配置文件的VVol数据存储库。其余VVol数据存储库将列在不兼容的数据存储库列表中。您可以忽略此分类、并从不兼容的数据存储库列表中选择任何VVol数据存储库来配置或修改虚拟机。

====