---
permalink: manage/concept-datastore-reports.html 
sidebar: sidebar 
keywords: datastore, reports, 
summary: 数据存储库报告提供了有关传统数据存储库以及在这些数据存储库上创建的虚拟机的详细信息。 
---
= 数据存储库报告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
数据存储库报告提供了有关传统数据存储库以及在这些数据存储库上创建的虚拟机的详细信息。

通过传统信息板，您可以查看和确定 vCenter Server 中的数据存储库和虚拟机可能存在的问题。您可以查看，排序和导出报告。传统数据存储库和虚拟机报告的数据由 vCenter Server 提供。

数据存储库提供以下预定义报告：

* 数据存储库报告
* 虚拟机报告




== 数据存储库报告

数据存储库报告菜单提供了有关数据存储库的以下参数的信息：

* 数据存储库的名称
* 数据存储库的类型： NFS 或 VMFS
* 可用空间
* 已用空间
* 总空间
* 已利用空间的百分比
* 可用空间百分比
* IOPS
+
此报告将显示数据存储库的 IOPS 。

* 延迟
+
此报告将显示数据存储库的延迟信息。



您还可以验证生成报告的时间。通过数据存储库报告菜单，您可以根据需要对报告进行组织，然后使用 * 导出到 CSV* 按钮导出已组织的报告。报告中的数据存储库名称是导航到选定数据存储库的 " 监控 " 选项卡的链接，您可以在此查看数据存储库性能指标。



== 虚拟机报告

虚拟机报告菜单为使用VSC为选定vCenter Server配置的数据存储库的所有虚拟机提供了以下性能指标：

* 虚拟机的名称
* 已提交容量
+
此报告将显示虚拟机的已提交容量值。

* 正常运行时间
+
此报告将显示虚拟机启动的时间以及 ESXi 主机上可用的时间。

* 延迟
+
此报告将显示与虚拟机关联的所有数据存储库中虚拟机的延迟。

* 电源状态
+
此报告将显示虚拟机是已启动还是已关闭。

* 主机
+
此报告将显示虚拟机可用的主机系统。



报告中的每个虚拟机名称都是指向选定虚拟机的 " 监控 " 选项卡的链接。您可以根据需要对虚拟机报告进行排序、并将此报告导出为`.CSV`文件、然后将其保存在本地系统上。报告的时间戳也会附加到保存的报告中。
