---
permalink: manage/task-set-default-credentials-for-storage-systems.html 
sidebar: sidebar 
keywords: setting, default, credentials, for, storage, systems, 
summary: 您可以使用适用于VMware vSphere的Virtual Storage Console为vCenter Server中的存储系统设置默认凭据。 
---
= 设置存储系统的默认凭据
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用适用于VMware vSphere的Virtual Storage Console为vCenter Server中的存储系统设置默认凭据。

您必须已选择要用于创建默认凭据的 vCenter Server 。

如果您为存储系统设置了默认凭据， Virtual Storage Console （ VSC ）将使用这些凭据登录到 VSC 刚刚发现的存储系统。如果默认凭据不起作用，您必须手动登录到存储系统。VSC 和 SRA 支持在集群级别或 SVM 级别添加存储系统凭据。但是， VASA Provider 只能使用集群级别的凭据。

.步骤
. 在VSC *主页*页面上、单击菜单：设置[管理设置>配置存储系统的默认凭据]。
. 在*存储系统默认凭据*对话框中、输入存储系统的用户名和密码。
+
存储控制器凭据会根据用户名和密码对在 ONTAP 中分配。存储控制器凭据可以是管理员帐户，也可以是使用基于角色的访问控制（ Role-Based Access Control ， RBAC ）的自定义帐户。

+
您不能使用 VSC 更改与存储控制器的用户名和密码对关联的角色。要修改或创建新的ONTAP 用户角色以用于VSC、VASA Provider和SRA的虚拟设备、您可以使用System Manager。

+
请参见适用于VMware®vSphere的Virtual Storage Console、VASA Provider和Storage Replication Adapter 9.7版部署和设置指南中的"`配置用户角色和权限`"一节。

. 单击 * 确定 * 以保存默认凭据。


如果由于存储系统报告"`Authentication Failure`"状态而更新了存储系统凭据、则应单击*存储系统*页面上的*重新发现全部*选项。执行此操作时， VSC 会尝试使用新凭据连接到存储系统。
