---
permalink: manage/task-configure-array-manager.html 
sidebar: sidebar 
keywords: configuring, sra, using, array, manager, 
summary: 您可以使用 Site Recovery Manager （ SRM ）的 Array Manager 向导配置 Storage Replication Adapter （ SRA ），以便在 SRM 和 Storage Virtual Machine （ SVM ）之间进行交互。 
---
= 使用阵列管理器配置 SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Site Recovery Manager (SRM)的*阵列管理器*向导配置Storage Replication Adapter (SRA)、以启用SRM与Storage Virtual Machine (SVM)之间的交互。

.开始之前
* 您必须已将 SRM 中的受保护站点和恢复站点配对。
* 在配置阵列管理器之前，您必须已配置存储。
* 您必须已在受保护站点和恢复站点之间配置和复制 SnapMirror 关系。
* 您必须已启用 SVM 管理 LIF 以启用多租户。


SRA 支持集群级别的管理和 SVM 级别的管理。如果您在集群级别添加存储，则可以发现集群中的所有 SVM 并对其执行操作。如果在 SVM 级别添加存储，则只能管理该特定 SVM 。

[NOTE]
====
VMware 不支持对 SRM 使用 NFS4.1 协议。

====
.步骤
. 在 SRM 中，单击 * 阵列管理器 * ，然后单击 * 添加阵列管理器 * 。
. 输入以下信息以描述 SRM 中的阵列：
+
.. 在 * 显示名称 * 字段中输入一个名称以标识阵列管理器。
.. 在 * SRA 类型 * 字段中，选择 * 适用于 ONTAP 的 NetApp 存储复制适配器 * 。
.. 输入要连接到集群或 SVM 的信息：
+
*** 如果要连接到集群，则应输入集群管理 LIF 。
*** 如果要直接连接到 SVM ，则应输入 SVM 管理 LIF 的 IP 地址。
+
[NOTE]
====
在配置阵列管理器时、您必须对存储系统使用与在Virtual Storage Console的*存储系统*菜单中添加存储系统时相同的连接和凭据。例如，如果阵列管理器配置的范围为 SVM ，则必须在 SVM 级别添加 VSC 下的存储。

====


.. 如果要连接到集群，请在 * SVM name* 字段中输入 SVM 的名称。
+
您也可以将此字段留空。

.. *可选：*在*卷包含列表*字段中输入要发现的卷。
+
您可以在受保护站点输入源卷，并在恢复站点输入复制的目标卷。您可以输入完整卷名称或部分卷名称。

+
例如、如果要发现与卷_dst_vol1_具有SnapMirror关系的卷_src_vol1_、则必须在受保护站点字段中指定_src_vol1_、并在恢复站点字段中指定_dst_vol1_。

.. *可选：*在*卷排除列表*字段中输入要从发现中排除的卷。
+
您可以在受保护站点输入源卷，并在恢复站点输入复制的目标卷。您可以输入完整卷名称或部分卷名称。

+
例如，如果要排除与卷 _dst_vol1_ 具有 SnapMirror 关系的卷 _src_vol1_ ，则必须在受保护站点字段中指定 _src_vol1_ ，并在恢复站点字段中指定 _dst_vol1_ 。

.. 在*用户名*字段中输入集群级别帐户或SVM级别帐户的用户名。
.. 在 * 密码 * 字段中输入用户帐户的密码。


. 单击 * 下一步 * 。
. 验证是否已发现阵列并将其显示在*添加阵列管理器*窗口的底部。
. 单击 * 完成 * 。


您可以使用相应的 SVM 管理 IP 地址和凭据对恢复站点执行相同的步骤。在*添加阵列管理器*向导的*启用阵列对*屏幕上、您应验证是否已选择正确的阵列对、并且该阵列对是否显示为已准备好启用。
