---
permalink: manage/task-map-storage-to-storage-capability-profiles.html 
sidebar: sidebar 
keywords: mapping, datastores, to, storage, capability, profiles, 
summary: 您可以将与适用于 ONTAP 的 VASA Provider 关联的数据存储库映射到存储功能配置文件。您可以将配置文件分配给未与存储功能配置文件关联的数据存储库。 
---
= 将数据存储库映射到存储功能配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将与适用于 ONTAP 的 VASA Provider 关联的数据存储库映射到存储功能配置文件。您可以将配置文件分配给未与存储功能配置文件关联的数据存储库。

.开始之前
* 您必须已向适用于VMware vSphere的Virtual Storage Console注册VASA Provider实例。
* Virtual Storage Console （ VSC ）必须已发现您的存储。


.关于此任务
您可以将传统数据存储库映射到存储功能配置文件，也可以更改与数据存储库关联的存储功能配置文件。VASA Provider不会在*存储映射*页面上显示任何虚拟卷(VVol)数据存储库。此任务中提及的所有数据存储库均为传统数据存储库。

.步骤
. 在VSC *主页*页面中、单击*存储映射*。
+
在*存储映射*页面中、您可以确定以下信息：

+
** 与数据存储库关联的 vCenter Server
** 与数据存储库匹配的配置文件数量
+
"*存储映射*"页面仅显示传统数据存储库。此页面不会显示任何 VVol 数据存储库或 qtree 数据存储库。

** 数据存储库当前是否与配置文件关联
+
一个数据存储库可以与多个配置文件匹配，但一个数据存储库只能与一个配置文件关联。

** 数据存储库是否符合与其关联的配置文件


. 要将存储功能配置文件映射到数据存储库或更改数据存储库的现有配置文件，请选择数据存储库。
+
要在*存储映射*页面上查找特定数据存储库或其他信息、您可以在搜索框中输入名称或部分字符串。VSC 将在对话框中显示搜索结果。要返回到完整显示内容，应删除搜索框中的文本，然后单击 * 输入 * 。

. 从*操作*菜单中、选择*分配匹配的配置文件*。
. 从 * 将配置文件分配给数据存储库 * 对话框中提供的匹配配置文件列表中选择要映射到数据存储库的配置文件，然后单击 * 确定 * 将选定配置文件映射到数据存储库。
. 刷新屏幕以验证新分配。

