---
permalink: manage/task-provision-datastores.html 
sidebar: sidebar 
keywords: provisioning, datastores, 
summary: 配置数据存储库会为虚拟机及其虚拟机磁盘（ VMDK ）创建一个逻辑容器。您可以配置数据存储库，然后将数据存储库连接到单个主机，集群中的所有主机或数据中心中的所有主机。 
---
= 配置数据存储库
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置数据存储库会为虚拟机及其虚拟机磁盘（ VMDK ）创建一个逻辑容器。您可以配置数据存储库，然后将数据存储库连接到单个主机，集群中的所有主机或数据中心中的所有主机。

.开始之前
* 要在直接连接到 Virtual Storage Console （ VSC ）的 SVM 上配置数据存储库，必须事先使用具有适当权限的用户帐户（而不是默认 vsadmin 用户帐户或 vsadmin 角色）将 SVM 添加到 VSC 中。
+
您也可以通过添加集群来配置数据存储库。

* 您必须确保在`kaminoprefs.xml`中输入ESXi托管的连接到的所有网络的子网详细信息。
+
请参见_VSC 9.6部署和设置指南_中的"在不同子网之间启用数据存储库挂载"一节。

* 如果您使用NFS或iSCSI、并且ESXi主机和存储系统的子网不同、则`kaminoprefs` preferences"文件中的NFS或iSCSI设置必须包括ESXi主机子网掩码。
+
此首选项文件也适用于创建VVol数据存储库。_Virtual Storage Console、VASA Provider和Storage Replication Adapter 9.6版部署和设置指南_提供了有关首选项文件以及在不同子网中启用数据存储库挂载的详细信息。

* 如果已启用 VASA Provider ，并且要为 NFS 数据存储库或 VMFS 数据存储库指定存储功能配置文件，则必须已创建一个或多个存储功能配置文件。
* 要创建 NFSv4.1 数据存储库，必须已在 SVM 级别启用 NFSv4.1 。


使用 * 配置数据存储库 * 选项可以为数据存储库指定存储功能配置文件。存储功能配置文件有助于指定一致的服务级别目标（ Service Level Objective ， SLO ）并简化配置过程。只有在启用了 VASA Provider 的情况下，才能指定存储功能配置文件。VSC、VASA Provider和SRA虚拟设备支持以下协议：

* NFSv3 和 NFSv4.1
* VMFS5 和 VMFS6


VSC 可以在 NFS 卷或 LUN 上创建数据存储库：

* 对于 NFS 数据存储库， VSC 会在存储系统上创建 NFS 卷，然后更新导出策略。
* 对于 VMFS 数据存储库， VSC 会创建一个新卷（如果选择了该选项，则会使用现有卷），然后创建一个 LUN 和一个 igroup 。


[NOTE]
====
VMware 不支持对数据存储库集群使用 NFSv4.1 。

====
如果在配置期间未指定存储功能配置文件，您可以稍后使用存储映射页面将数据存储库映射到存储功能配置文件。

.步骤
. 您可以使用以下方法之一访问数据存储库配置向导：
+
[cols="1a,1a"]
|===
| 选择项 | 执行以下操作... 


 a| 
* vSphere Client主页*
 a| 
.. 单击 * 主机和集群 * 。
.. 在导航窗格中，选择要配置数据存储库的数据中心。
.. 要指定要挂载数据存储库的主机，请参见下一步。




 a| 
* Virtual Storage Console主页*
 a| 
.. 单击 * 概述 * 。
.. 单击 * 入门 * 选项卡。
.. 单击 * 配置 * 按钮。
.. 单击 * 浏览 * 以选择要按下一步配置数据存储库的目标。


|===
. 指定要挂载数据存储库的主机。
+
[cols="1a,1a"]
|===
| 使数据存储库可用于... | 执行此操作 ... 


 a| 
数据中心中的所有主机
 a| 
右键单击某个数据中心、然后选择菜单：NetApp VSC[配置数据存储库]。



 a| 
集群中的所有主机
 a| 
右键单击主机集群、然后选择菜单：NetApp VSC[配置数据存储库]。



 a| 
一台主机
 a| 
右键单击某个主机、然后选择菜单：NetApp VSC[配置数据存储库]。

|===
. 完成*新建数据存储库*对话框中的字段以创建数据存储库。
+
对话框中的大多数字段都是不言自明的。下表介绍了一些可能需要指导的字段。

+
[cols="1a,1a"]
|===
| 部分 | Description 


 a| 
常规
 a| 
"新建数据存储库配置*"对话框的*常规*部分提供了用于输入新数据存储库的目标、名称、大小、类型和协议的选项。您可以选择 * NFS * 或 * VMFS* 协议来配置传统数据存储库。VVol数据存储库类型用于配置VVol数据存储库。如果启用了 VASA Provider ，则还可以决定是否使用存储功能配置文件。* 数据存储库集群 * 选项仅适用于传统数据存储库。您应使用 * 高级 * 选项指定 * VMFS5* 或 * VMFS6* 文件系统。



 a| 
存储系统
 a| 
如果在*常规*部分中选择了选项、则可以选择列出的存储功能配置文件之一。存储系统和 Storage Virtual Machine 的系统建议值已填充，以便于使用。但是，如果需要，您可以修改这些值。



 a| 
存储属性
 a| 
默认情况下， VSC 会填充 * 聚合 * 和 * 卷 * 选项的建议值。您可以根据自己的要求自定义这些值。此外，还会填充 * 高级 * 菜单下的 * 空间预留 * 选项，以获得最佳结果。



 a| 
摘要
 a| 
您可以查看为新数据存储库指定的参数摘要。

|===
. 在*摘要*部分中、单击*完成*。

